services:
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    app.admin.operation:
        class: AppBundle\Admin\OperationAdmin
        arguments: [~, AppBundle\Entity\Operation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Operation}

    app.admin.instance:
        class: AppBundle\Admin\InstanceAdmin
        arguments: [~, AppBundle\Entity\Instance, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Instance}

    app.admin.instance_modification:
        class: AppBundle\Admin\InstanceModificationAdmin
        arguments: [~, AppBundle\Entity\InstanceModification, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: InstanceModification}

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    app.admin.group:
        class: AppBundle\Admin\GroupAdmin
        arguments: [~, AppBundle\Entity\Group, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Group}
