services:
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    app.admin.operation:
        class: AppBundle\Admin\OperationAdmin
        arguments: [~, AppBundle\Entity\Operation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Operation}

    app.admin.operation_modification:
        class: AppBundle\Admin\OperationModificationAdmin
        arguments: [~, AppBundle\Entity\OperationModification, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: OperationModification}
