categories:
    type:     rest
    name_prefix:  api_
    resource: AppBundle\Controller\Api\CategoryController
operations:
    type:     rest
    name_prefix:  api_
    resource: AppBundle\Controller\Api\OperationController
instances:
    type:     rest
    name_prefix:  api_
    resource: AppBundle\Controller\Api\InstanceController
modifications:
    type:     rest
    name_prefix:  api_
    resource: AppBundle\Controller\Api\ModificationController
calendar:
    type:     rest
    name_prefix:  api_
    resource: AppBundle\Controller\Api\CalendarController
